;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================


[colors]
;background = ${xrdb:color0:#222}
;background = #CC333333
background = #00fdf6e3
background-module= #00fdf6e3
background-alt= #fdf6e3
foreground = #fdf6e3
foreground-alt = #fdf6e3
primary = #fdf6e3
secondary = #fdf6e3
alert = #00fdf6e3
spacer = 15
icon = #fdf6e3

[bar/lower]
height = 25
width = 100%
offset-x = 0
offset-y = 0
radius = 0.0
fixed-center = true

bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 15
border-color = #00FFFFFF

padding-left = 10
padding-right = 10

module-margin-left = 0
module-margin-right = 0

font-0 = MonoLisa i3b4cx:style=Bold Italic:size=9
font-1 = MonoLisa i3b4cx:style=Bold Italic:size=9
font-2 = Material Icons:style=Regular:size=9

modules-left = sshfs filesystem memory cpu
modules-center = xkeyboard
modules-right = pulseaudio temperature battery wlan eth

tray-position = none

cursor-click = pointer
cursor-scroll = ns-resize

[bar/upper]
height = 25
width = 100%
offset-x = 0
offset-y = 0
radius = 0.0
fixed-center = true

bottom = false

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 15
border-color = #00FFFFFF

padding-left = 10
padding-right = 10

font-0 = MonoLisa i3b4cx:style=Bold Italic:size=9
font-1 = MonoLisa i3b4cx:style=Bold Italic:size=9
font-2 = Material Icons:style=Regular:size=9

modules-left = i3
modules-center = xwindow
modules-right = date

tray-position = none

cursor-click = pointer
cursor-scroll = ns-resize

[module/xwindow]
type = internal/xwindow
label = "   %title:0:100:...%   "
format-background = ${colors.background-module}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = ""

label-indicator-padding = 2
label-indicator-background = ${colors.background-module}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = "     %free%   "
label-mounted-background = ${colors.background-module}

label-unmounted = ""
label-unmounted-foreground = ${colors.foreground-alt}
format-mounted-offset = ${colors.spacer}
format-unmount-offset = ${colors.spacer}

[module/sshfs]
type = internal/fs
interval = 25

mount-0 = /mnt/sshfs

label-mounted = "     %free%   "
label-mounted-background = ${colors.background-module}
label-mounted-foreground = ${colors.background-alt}
label-unmounted = "     disconnected   "
label-unmounted-background = ${colors.background-module}
label-unmounted-foreground = ${colors.background-alt}

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
format-margin = 0

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.background-module}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.background-module}
label-focused-foreground = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2
label-focused-margin = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 2
label-unfocused-margin = 2
label-unfocused-background = ${colors.background-module}
label-unfocused-foreground = ${colors.background-alt}

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

; Separator in between workspaces
label-separator = |


[module/mpd]
type = internal/mpd
;format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>
format-online = <label-song>
;format-online-background = #00000000
;format-online-foreground = #88000000
format-online-background = ${colors.background-module}
;format-online-padding = 3

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

;label-song = %artist% - %album% - %title%
label-song = "   %title%   "
label-song-maxlen = 80
label-song-ellipsis = true

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 2
;format-prefix = "   "
;format-prefix-foreground = #0098ff
;format-underline = #0098ff
label = "     %percentage:02%%   "
format-background = ${colors.background-module}
;format-padding = 2
format-offset = ${colors.spacer}

[module/memory]
type = internal/memory
interval = 2
;format-prefix = "    "
;format-prefix-foreground = #b500e2
label = "     %mb_free%   "

format-background = ${colors.background-module}
;format-padding = 2
format-offset = ${colors.spacer}

[module/wlan]
type = internal/network
interface = wlp9s0
interval = 3.0

;format-connected-prefix = "    "
format-connected = <label-connected>
;format-connected-underline = #AAAAEE
label-connected = "     %local_ip% %signal%%   "
format-connected-offset = ${colors.spacer}
format-connected-prefix-foreground = #ffffff

format-connected-background = ${colors.background-module}

format-disconnected-underline = ${self.format-connected-underline}
label-disconnected = "%ifname% disconnected   "
label-disconnected-foreground = ${colors.background-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = eno1
interval = 3.0

;format-connected-underline = #AAAAEE
format-connected-prefix = "E "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = "%local_ip%   "
format-connected-offset = ${colors.spacer}

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1

date = "%m/%d/%y"
date-alt = "%m/%d/%Y"

time = %H:%M:%S
time-alt = %H:%M:%S

;format-prefix = "    "
;format-prefix-foreground = #E5E5F5
;format-underline = #E5E5F5
;format-offset = ${colors.spacer}
;format-background = #000
;
format-background = ${colors.background-module}
;format-padding = 2

label = " %time%     %date% "

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true

format-volume = <ramp-volume> <label-volume>
label-volume = " %percentage%%   "
label-volume-foreground = ${root.foreground}

label-muted =  muted   
label-muted-foreground = ${colors.background-alt}

; 0% = muted, 1-33% = low, 34-66% = medium, 67-100% = high
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-4 = 
ramp-volume-5 = 
ramp-volume-6 = 
ramp-volume-7 = 
ramp-volume-8 = 
ramp-volume-9 = 
ramp-volume-10 = 
ramp-volume-11 = 
ramp-volume-12 = 
ramp-volume-13 = 
ramp-volume-14 = 
ramp-volume-15 = 
ramp-volume-16 = 
ramp-volume-17 = 
ramp-volume-18 = 
ramp-volume-19 = 
ramp-volume-20 = 
ramp-volume-21 = 
ramp-volume-22 = 
ramp-volume-23 = 
ramp-volume-24 = 
ramp-volume-25 = 
ramp-volume-26 = 
ramp-volume-27 = 
ramp-volume-28 = 
ramp-volume-29 = 
ramp-volume-30 = 
ramp-volume-31 = 
ramp-volume-32 = 
ramp-volume-33 = 
ramp-volume-34 = 
ramp-volume-35 = 
ramp-volume-36 = 
ramp-volume-37 = 
ramp-volume-38 = 
ramp-volume-39 = 
ramp-volume-40 = 
ramp-volume-41 = 
ramp-volume-42 = 
ramp-volume-43 = 
ramp-volume-44 = 
ramp-volume-45 = 
ramp-volume-46 = 
ramp-volume-47 = 
ramp-volume-48 = 
ramp-volume-49 = 
ramp-volume-50 = 
ramp-volume-51 = 
ramp-volume-52 = 
ramp-volume-53 = 
ramp-volume-54 = 
ramp-volume-55 = 
ramp-volume-56 = 
ramp-volume-57 = 
ramp-volume-58 = 
ramp-volume-59 = 
ramp-volume-60 = 
ramp-volume-61 = 
ramp-volume-62 = 
ramp-volume-63 = 
ramp-volume-64 = 
ramp-volume-65 = 
ramp-volume-66 = 
ramp-volume-67 = 
ramp-volume-68 = 
ramp-volume-69 = 
ramp-volume-70 = 
ramp-volume-71 = 
ramp-volume-72 = 
ramp-volume-73 = 
ramp-volume-74 = 
ramp-volume-75 = 
ramp-volume-76 = 
ramp-volume-77 = 
ramp-volume-78 = 
ramp-volume-79 = 
ramp-volume-80 = 
ramp-volume-81 = 
ramp-volume-82 = 
ramp-volume-83 = 
ramp-volume-84 = 
ramp-volume-85 = 
ramp-volume-86 = 
ramp-volume-87 = 
ramp-volume-88 = 
ramp-volume-89 = 
ramp-volume-90 = 
ramp-volume-91 = 
ramp-volume-92 = 
ramp-volume-93 = 
ramp-volume-94 = 
ramp-volume-95 = 
ramp-volume-96 = 
ramp-volume-97 = 
ramp-volume-98 = 
ramp-volume-99 = 

bar-volume-width = 10
bar-volume-foreground-0 = ${colors.background-alt}
bar-volume-foreground-1 = ${colors.background-alt}
bar-volume-foreground-2 = ${colors.background-alt}
bar-volume-foreground-3 = ${colors.background-alt}
bar-volume-foreground-4 = ${colors.background-alt}
bar-volume-foreground-5 = ${colors.background-alt}
bar-volume-foreground-6 = ${colors.background-alt}
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/alsa]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = VOL
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = sound muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 100
time-format = %H:%M

label-charging = "     %percentage%% %time%   "
format-charging = <label-charging>
;format-charging-underline = #16ba62
format-charging-offset = ${colors.spacer}
;format-charging-prefix = "    "
;format-charging-prefix-foreground = #16ba62

format-charging-background = ${colors.background-module}
;format-charging-padding = 2

label-discharging = "     %percentage%% %time%   "
format-discharging = <label-discharging>
;format-discharging-underline = ${self.format-charging-underline}
format-discharging-offset = ${colors.spacer}
;format-discharging-prefix = "    "
;format-discharging-prefix-foreground = #16ba62
format-discharging-background = ${colors.background-module}
;format-discharging-padding = 2

label-full = "     %percentage%% 00:00   "
format-full = <label-full>
;format-full-prefix = "    "
;format-full-prefix-foreground = #16ba62
;format-full-underline = ${self.format-charging-underline}
format-full-offset = ${colors.spacer}
format-full-background = ${colors.background-module}
;format-full-padding = 2


ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 1
animation-charging-1 = 2
animation-charging-2 = 3
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 1
animation-discharging-1 = 2
animation-discharging-2 = 3
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

[module/whoami]
type = custom/script
exec = echo $(whoami)@$(hostname) $(uname -sr)
interval = 1000000
format-background = #00000000
format-foreground = #000
format-padding = 3

[module/nvidiaclock]
type = custom/script
exec = printf "%4s MHz " $(nvidia-settings -q gpucurrentclockfreqs -t | cut -d, -f1 | head -n1)
interval = 10
format-underline = #16ba62
format-offset = ${colors.spacer}
format-prefix = "G "
format-prefix-foreground = ${colors.foreground-alt}

[module/nvidiatemp]
type = custom/script
exec = nvidia-settings -q gpucoretemp -t | head -n1 | sed s/$/°C/
interval = 10
format-underline = #16ba62

[module/temperature]
type = internal/temperature
warn-temperature = 55
hwmon-path = /sys/class/hwmon/hwmon0/temp1_input

;format-prefix = " "
;format-prefix-foreground = #f1535a

format = <label>
format-background = ${colors.background-module}

;format-warn-prefix = " "
;format-warn-prefix-foreground = ${colors.secondary}

format-warn = <label-warn>
format-warn-background = ${colors.background-module}

;format-offset = -10

;format-padding = 2

label = "     %temperature-c%   "
label-warn = "     %temperature-c%   "
;label-warn-foreground = ${colors.secondary}
format-offset = ${colors.spacer}

ramp-0 = 0
ramp-1 = 1
ramp-2 = 2
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = OPEN
label-open-foreground = ${colors.secondary}
label-close = CANCEL
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 0
margin-bottom = 0

; vim:ft=dosini
